jobs:
  my_job:
    runs-on: windows-latest
    steps:
      - name: Access Secret
        env:
          AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.AUTH_PROVIDER_X509_CERT_URL }}
          AUTH_URI: ${{ secrets.AUTH_PROVIDER_X509_CERT_URL }}
          CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_X509_CERT_URL: ${{ secrets.CLIENT_X509_CERT_URL }}
          DB_TYPE: ${{ secrets.DB_TYPE }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          TOKEN_URI: ${{ secrets.TOKEN_URI }}
          UNIVERSE_DOMAIN: ${{ secrets.UNIVERSE_DOMAIN }}